#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 24 10:21:06 2020

@author: fenilmavani
"""

import calendar


c = calendar.TextCalendar(calendar.MONDAY)
st = c.formatmonth(2020, 1,0,0)
print(st)



hc = calendar.HTMLCalendar(calendar.SUNDAY)

st = hc.formatyear(2020)

print(st)





for i in c.itermonthdays(2017,4):
    print(i)
    
    
    
for name in calendar .month_name:
    print(name)
    
for day in calendar.day_name:
    print(day)



print("Classses will be on")
for c in range(1,13):
    cal = calendar.monthcalendar(2020, c)
    weekone = cal[0]
    weektwo = cal[1]
    
    
    if weekone[calendar.FRIDAY] != 0:
        classday = weekone[calendar.FRIDAY]
    else:
        classday = weektwo[calendar.FRIDAY]
        
    print("%10s %2d" %(calendar.month_name[c], classday))        
        