#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 23 23:37:21 2020

@author: fenilmavani
"""

from datetime import datetime



def main():
    now = datetime.now()
    print(now.strftime("%a, %d, %b, %y"))
    
    
    
    print(now.strftime("Locale date and time: %c"))
    print(now.strftime("Locale date : %x"))
    print(now.strftime("Locale time: %X"))
    
    
    print(now.strftime("Current time: %I:%M:%S %p"))
    print(now.strftime("24-hrs time: %H:%M "))
    
    
    
main()    
    